// <auto-generated />
using System;
using HotelGuru.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelGuru.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250323160401_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Bankkartya")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Telefonszam")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");

                    b.HasDiscriminator().HasValue("Felhasznalo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FoglalasIdopontja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoglaltSzobaID")
                        .HasColumnType("int");

                    b.Property<bool>("HitelesBankkartya")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Foglalasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.PluszSzolgaltatas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SzolgaltatasAra")
                        .HasColumnType("int");

                    b.Property<string>("SzolgaltatasLeiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzolgaltatasNeve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PluszSzolgaltatasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Szoba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AgyakSzama")
                        .HasColumnType("int");

                    b.Property<int>("EjszakaAr")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Szobak");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Recepcios", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.HasDiscriminator().HasValue("Recepcios");
                });
#pragma warning restore 612, 618
        }
    }
}
