// <auto-generated />
using System;
using HotelGuru.DataContext.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelGuru.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250514074615_szamlak")]
    partial class szamlak
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Felhasznalo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bankkartya")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nev")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefonszam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("jelszo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("szerep")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Felhasznalok");

                    b.HasDiscriminator().HasValue("Felhasznalo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Foglalas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Belepve")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Erkezes")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoSzam")
                        .HasColumnType("int");

                    b.Property<DateTime>("FoglalasIdopontja")
                        .HasColumnType("datetime2");

                    b.Property<int>("FoglaloId")
                        .HasColumnType("int");

                    b.Property<int>("FoglaltSzobaID")
                        .HasColumnType("int");

                    b.Property<bool>("HitelesBankkartya")
                        .HasColumnType("bit");

                    b.Property<int>("PluszSzolgId")
                        .HasColumnType("int");

                    b.Property<int>("SzamlaId")
                        .HasColumnType("int");

                    b.Property<int>("SzobaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tavozas")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visszaigazolva")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("FoglaloId");

                    b.HasIndex("SzobaId");

                    b.ToTable("Foglalasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.PluszSzolgaltatas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("SzolgaltatasAra")
                        .HasColumnType("int");

                    b.Property<string>("SzolgaltatasLeiras")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SzolgaltatasNeve")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PluszSzolgaltatasok");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Szamla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FelhasznaloId")
                        .HasColumnType("int");

                    b.Property<int>("FoglalasId")
                        .HasColumnType("int");

                    b.Property<int>("PluszSzolgId")
                        .HasColumnType("int");

                    b.Property<int>("SzobaId")
                        .HasColumnType("int");

                    b.Property<int>("VegsoAr")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Szamlak");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Szoba", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AgyakSzama")
                        .HasColumnType("int");

                    b.Property<int>("EjszakaAr")
                        .HasColumnType("int");

                    b.Property<string>("Felszereltseg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Statusz")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Szobak");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Adminisztrator", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.HasDiscriminator().HasValue("Adminisztrator");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Recepcios", b =>
                {
                    b.HasBaseType("HotelGuru.DataContext.Entities.Felhasznalo");

                    b.HasDiscriminator().HasValue("Recepcios");
                });

            modelBuilder.Entity("HotelGuru.DataContext.Entities.Foglalas", b =>
                {
                    b.HasOne("HotelGuru.DataContext.Entities.Felhasznalo", "Foglalo")
                        .WithMany()
                        .HasForeignKey("FoglaloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelGuru.DataContext.Entities.Szoba", "Szoba")
                        .WithMany()
                        .HasForeignKey("SzobaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Foglalo");

                    b.Navigation("Szoba");
                });
#pragma warning restore 612, 618
        }
    }
}
